---
#
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

# Magma files collection based on map paths_to_collect
- name: Create a dest directory for magma files under report directory
  file:
    path: "{{report_dir_output.stdout}}/{{item.relative_dest}}"
    state: directory
    mode: "0700"
  loop: "{{paths_to_collect}}"


- debug:
    msg: "{{ item }}"
  loop: "{{ paths_to_collect | community.general.json_query('[*].src') }}"


- name: Copy magma files to destination
  copy:
    src: "{{item}}"
    dest: "{{report_dir_output.stdout }}/{{item}}"
  with_fileglob: "{{ paths_to_collect | community.general.json_query('[*].src') }}"
